---
--- Generated by Luanalysis
--- Created by Lenovo.
--- DateTime: 2023/1/5 17:03
---
local cmdQueue = {} -- 挂起操作的队列
local lib = {}
function lib.readline(stream, callback)
    local nextCmd = function()
        callback(stream:read())
    end
    table.insert(cmdQueue, nextCmd)
end
function lib.write(stream, line, callback)
    local nextCmd = function()
        callback(stream:write(line))
    end
    table.insert(cmdQueue, nextCmd)
end
function lib.stop()
    table.insert(cmdQueue, "stop")
end
function lib.runloop()
    while true do
        local nextCmd = table.remove(cmdQueue, 1)
        if nextCmd == "stop" then
            break
        else
            nextCmd()
        end

    end
end
return lib