---
--- Generated by Luanalysis
--- Created by Lenovo.
--- DateTime: 2022/12/30 17:51
---
-- 对偶表示实现私有性
local balance = {}
Account = {}
function Account:withdraw(v)
    balance[self] = balance[self] - v
end

function Account:deposit(v)
    balance[self] = balance[self] + v
end

function Account:balance()
    return balance[self]
end

function Account:new(o)
    o = o or {}
    setmetatable(o, self)
    self.__index = self
    balance[o] = 0
    return o
end
a = Account:new({})
a:deposit(100.00)
print(a:balance())
-- 用户只能通过提供的和balance相关的方法进行访问，不能直接修改balance
-- 这种方法的缺点主要是性能上的，比如gc就会受到影响，需要额外操作