---
--- Generated by Luanalysis
--- Created by Lenovo.
--- DateTime: 2023/3/19 20:21
---
a = { 1, 2, 3, [1] = "hello", [3] = "abc", 4 }
print("pairs")
for k, v in pairs(a) do
    print("k: " .. k .. ", v: " .. v)
end
print("ipairs")
for k, v in ipairs(a) do
    print("k: " .. k .. ", v: " .. v)
end
print("--------------------------------")
b = 1, 2, 3
print(b)