---
--- Generated by Luanalysis
--- 使用事件驱动方式逆序一个文件
--- Created by Lenovo.
--- DateTime: 2022/12/17 20:18
---
local lib = require("async-lib")
local t = {}
local inp = io.input()
local out = io.output()
local i

local function putline()
    i = i - 1
    if i == 0 then
        lib.stop()
    else
        lib.write(out, t[i] .. "\n", putline)
    end
end

local function getline(line)
    if line then
        t[#t + 1] = line
        lib.readline(inp, getline)
    else
        i = #t + 1
        putline()
    end
end
lib.readline(inp, getline)
lib.runloop()